version: '3.9'
services:
  couchbase-master:
    image: couchbase
    ports:
      - 8091:8091 # couchbase admin client
      - 8092:8092 # couchbase query client
      - 8093:8093 # couchbase index service
      - 8094:8094 # couchbase query service
    #   - 11210:11210 # client data access
    #   - 18091:18091 # couchbase admin client https
    restart: always
    networks:
      - couchbase-network
    environment:
      TYPE: MASTER
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: admin1234
    volumes:
      - couchbase-data:/opt/couchbase/var

networks:
  couchbase-network:
    driver: bridge

volumes:
  couchbase-data:
    driver: local
