version: '3.9'
services:
  couchbase-worker:
    image: couchbase
    restart: always
    environment:
      TYPE: WORKER
      COUCHBASE_MASTER: couchbase-master
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: admin1234
    networks:
      - couchbase-network
    volumes:
      - couchbase-data:/opt/couchbase/var

networks:
  couchbase-network:
    driver: bridge

volumes:
  couchbase-data:
    driver: local
